### ISSUE TITLE
Abgabe Schlussbericht Sonntag 28.5.23 / 23.59

### ISSUE THREAD

**Issue by hombinator** [TopInvestor4000/ResourceMaster#41]
Bitte Dokumente korrekt benennen: Name der Gruppe_Name Kommunikationsdoz_Schlussbericht_PM4_FS23:
Z.B. Shubidu_zubj_Schlussbericht_PM4_FS23

Die Note für den sprachlichen Teil des Schlussberichts erhalten Sie schriftlich im Rahmen der Notenabgabe von ihren Fachdozierenden.

**Comment by hombinator** [comment]
https://www.overleaf.com/project/6464f07341aaf0343fce61ef

**Comment by hombinator** [comment]
https://moodle.zhaw.ch/pluginfile.php/1019969/mod_resource/content/6/SW03%20Einfu%CC%88hrung%20SW3_Version230227.pdf

Seite 12

**Comment by flo-graf** [comment]
todo: 

- remove "our" from report - make it impersonal
- what goals did we not achieve? - report sounds a bit too good to be true
- make sure actual results in the app match described results in the text
- reduce length of intro, results, discussion to 5-7 pages
- align abstract with ZHAW guidlines
